import { TextAttributes } from "@opentui/core";
import { createMemo } from "solid-js";

import { KeyHintStrip } from "../../components/key-hint-strip";
import { EDITOR_KV_HINTS } from "../../keyboard/keybindings";
import { KVTable } from "../../components/kv-table";
import {
	activeRequest,
	commitEditingValue,
	editing,
	headersCursor,
	theme,
	updateEditingDraft,
} from "../../state/store";
import { vars } from "../../utils/highlight";

export function HeadersTab() {
	const t = () => theme();
	const r = activeRequest;

	const decoratedHeaders = createMemo(() => {
		const cur = headersCursor();
		return r().headers.map((h, i) => ({
			...h,
			value: vars(h.value),
			rawValue: h.value,
			cursor: cur.row === i,
		}));
	});

	const addRowCursor = () => headersCursor().row === r().headers.length;

	return (
		<box flexDirection="column" flexGrow={1}>
			<KVTable
				rows={decoratedHeaders()}
				noDesc
				showAddRow
				addLabel="+ key"
				addRowCursor={addRowCursor()}
				showDeleteColumn
				cursorCol={headersCursor().col}
				editing={editing()?.tab === "Headers" ? editing()! : undefined}
				onEditInput={updateEditingDraft}
				onEditSubmit={commitEditingValue}
			/>

			<box flexDirection="column" flexShrink={0} paddingTop={1}>
				<box flexDirection="row" height={1}>
					<text width={2}>{"  "}</text>
					<text fg={t().textDim} attributes={TextAttributes.DIM}>
						auto-generated (Host, User-Agent, Accept-Encoding…)
					</text>
				</box>
				<KVTable rows={autoGeneratedHeaders} noDesc noHeader />
			</box>

			<box flexGrow={1} />
			<KeyHintStrip items={EDITOR_KV_HINTS} />
		</box>
	);
}

const autoGeneratedHeaders = [
	{
		key: "Host",
		value: "jsonplaceholder.typicode.com",
		enabled: true,
		muted: true,
	},
	{
		key: "User-Agent",
		value: "tuipostman/0.4.1",
		enabled: true,
		muted: true,
	},
	{
		key: "Accept-Encoding",
		value: "gzip, deflate, br",
		enabled: true,
		muted: true,
	},
];
